"""Module that consists of all constants"""

NUM_OF_DEFUSE_CARDS_IN_BASE_GAME = 6
NUM_OF_ATTACK_CARDS_IN_BASE_GAME = 4
NUM_OF_SHUFFLE_CARDS_IN_BASE_GAME = 4
NUM_OF_SEE_FUTURE_CARDS_IN_BASE_GAME = 5
NUM_OF_NOPE_CARDS_IN_BASE_GAME = 5
NUM_OF_SKIP_CARDS_IN_BASE_GAME = 4
NUM_OF_FAVOR_CARDS_IN_BASE_GAME = 4
NUM_OF_TACOCAT_CARDS_IN_BASE_GAME = 4
NUM_OF_CATERMELON_CARDS_IN_BASE_GAME = 4
NUM_OF_HAIRY_POTATO_CAT_CARDS_IN_BASE_GAME = 4
NUM_OF_BEARD_CAT_CARDS_IN_BASE_GAME = 4
NUM_OF_RAINBOW_RALPHING_CAT_CARDS_IN_BASE_GAME = 4